[MQTT_CONFIG]
bemfa_broker=bemfa.com
bemfa_port=9501
# 巴法平台的主题名/设备名
bemfa_topic=pc006
# 巴法平台控制台获取的私钥
bemfa_client_id=b******************************5

[WOL_CONFIG]
# 目标主机的MAC地址，windows下打开CMD输入命令ipconfig /all查看
wol_mac=4E:C0:5A:3B:F1:2D
# 目标主机的IP地址，windows下打开CMD输入命令ipconfig /all查看
wol_ip=192.168.1.100
# 目标主机的用户名
wol_user=administrator
# 目标主机的密码
wol_password=password
